package wqc.mapper;


import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;
import wqc.example.HotelUserExample;
import wqc.model.HotelUserModel;

import java.util.List;

/**
 * @ClassName: HotelUserMapper
 * @Description: 酒店房间管理系统
 * @Author: wqc
 * @Date: 2022/2/28 21:03
 **/
@Mapper
public interface HotelUserMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hotel_user
     *
     * @mbg.generated Wed Mar 02 14:18:10 UTC 2022
     */
    long countByExample(HotelUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hotel_user
     *
     * @mbg.generated Wed Mar 02 14:18:10 UTC 2022
     */
    int deleteByExample(HotelUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hotel_user
     *
     * @mbg.generated Wed Mar 02 14:18:10 UTC 2022
     */
    int deleteByPrimaryKey(Long userId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hotel_user
     *
     * @mbg.generated Wed Mar 02 14:18:10 UTC 2022
     */
    int insert(HotelUserModel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hotel_user
     *
     * @mbg.generated Wed Mar 02 14:18:10 UTC 2022
     */
    int insertSelective(HotelUserModel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hotel_user
     *
     * @mbg.generated Wed Mar 02 14:18:10 UTC 2022
     */
    List<HotelUserModel> selectByExample(HotelUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hotel_user
     *
     * @mbg.generated Wed Mar 02 14:18:10 UTC 2022
     */
    HotelUserModel selectByPrimaryKey(Long userId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hotel_user
     *
     * @mbg.generated Wed Mar 02 14:18:10 UTC 2022
     */
    int updateByExampleSelective(@Param("record") HotelUserModel record, @Param("example") HotelUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hotel_user
     *
     * @mbg.generated Wed Mar 02 14:18:10 UTC 2022
     */
    int updateByExample(@Param("record") HotelUserModel record, @Param("example") HotelUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hotel_user
     *
     * @mbg.generated Wed Mar 02 14:18:10 UTC 2022
     */
    int updateByPrimaryKeySelective(HotelUserModel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hotel_user
     *
     * @mbg.generated Wed Mar 02 14:18:10 UTC 2022
     */
    int updateByPrimaryKey(HotelUserModel record);
}
